use Biblioteca;
select * from membru;
select * from carte;
select * from opera;
select * from tiparita;
select * from manuscris;
select * from rezervare_online;
select * from istoric_imprumut;
select * from imprumut_curent;
select * from participare_eveniment;
select * from eveniment;
select * from sala_studiu;
select * from angajat;
select * from acces_sala;
